build as a separate command
due to openshift timeouts, starting the app requires manual help

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -15,7 +15,6 @@ function start() {
   fi
   cd "$OPENSHIFT_REPO_DIR"/web
   echo "Starting $OPENSHIFT_APP_NAME"
-  build
   elixir --detached -e "File.write! '$pid_file', :os.getpid" -S mix phoenix.server
   ret=$?
   if [ ! "$ret" -eq 0 ]; then
@@ -72,7 +71,7 @@ function status() {
 function build() {
   cd "$OPENSHIFT_REPO_DIR"/web
   echo "building $OPENSHIFT_APP_NAME"
-  #(yes | elixir -S mix phoenix.init) || echo "ignore the error, it is makeshift workaround to compile dependencies"
+  (yes | elixir -S mix phoenix.init) || echo "ignore the error, it is makeshift workaround to compile dependencies"
   echo "building $OPENSHIFT_APP_NAME finished"
 }
 
