debug without build

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -72,7 +72,7 @@ function status() {
 function build() {
   cd "$OPENSHIFT_REPO_DIR"/web
   echo "building $OPENSHIFT_APP_NAME"
-  (yes | elixir -S mix phoenix.init) || echo "ignore the error, it is makeshift workaround to compile dependencies"
+  #(yes | elixir -S mix phoenix.init) || echo "ignore the error, it is makeshift workaround to compile dependencies"
   echo "building $OPENSHIFT_APP_NAME finished"
 }
 
